import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import "./globals.css";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import ModalProviders from "@/providers/modal-providers";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProviders />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
